### ISSUE TITLE
unable to use rasterizeHTML with MathJax

### ISSUE THREAD

**Issue by askalski** [cburgmer/rasterizeHTML.js#100]
Hi,

I have a website that uses a lot of MathML with MathJax, in SVG configuration (since other one has a issue with Bootstrap).

To make it work with rasterizeHTML I modified the server to serve MathJax.js from the same origin, and I used both like this:

rasterizeHTML.drawURL("theURLwithMathJax", document.createElement("CANVAS"), { executeJs : true }).then(function success(renderResult) {
		alert("supa");
		window.rr = renderResult
      }, function error(e) {
		alert("dupa");
      });

Then Chromium gave me error about some iframe not having "allow-scripts", so I grabbed the rasterizeHTML code and added it (and errors disappeared). Now matter whether with or without the errors, I was able to access window.rr.image, but judging from what I have seen, MathJax have not been executed. Adding timeout did not help.

What am I doing wrong? Or is there a workaround?

Kindest Regards
Andrzej Skalski

**Comment by cburgmer** [comment]
Hi, sorry for the late answer.

About the 'allow-scripts'. Iframes are internally used for different purposed. One of them is just to calculate the constraints of the viewport, and no script execution is wanted there, that's the reason for the given setting. The warnings can be safely ignored.

To help debug, did you check whether the renderResult returns any additional load errors? Similar to a browser rasterizeHTML.js is able to render a page, even if some of the resources fail. Such failures are reported in an additional list.

It would help if you could minimize the overall setup, to provide a minimal test case. Probably you don't even need the dependency that you are using, but you can replace it with a minimal handcrafted JavaScript file.

**Comment by askalski** [comment]
Hi,

thank you for your answer. While I was working on a minimal demo (which would be big since I would have to bundle MathJax with it) I observed it is indeed working with MathJax. So it's some other library to blame. I apologize for false ticket, and I thank you for your willingness to look into it.

Kindest Regards
Andrzej Skalski

**Comment by askalski** [comment]
figured out what was broken:
this tag
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4`/css/bootstrap.min.css">
was not closed. Changing it to this:

`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"></link>`

fixed problem.

**Comment by cburgmer** [comment]
Thanks for the feedback. 

Not closing `<link>` is valid HTML, so you should be fine generally speaking. Is you HTML input  actually XHTML (in which case you do need to close)? Otherwise it might be a bug we should fix.

**Comment by askalski** [comment]
here's the example:

https://mega.nz/#!cQ5kQBhK!iMFEvqxiC68ew3b_FRCxcAHesHxb2QgCUjNDjGUC3pc

it contains MathJax so it's big.

there's one file, index.html, and removing </link> makes rasterizeHTML.js stop working.

**Comment by askalski** [comment]
yeah, so my output is HTML5, where the `</link>` is actually forbidden ( http://www.w3.org/TR/html401/struct/links.html#edef-LINK ), and with that as a input rasterizeHTML.js fails. Is there a workaround? Can I - for instance - provide a pre-processing method for a separate URL?

**Comment by cburgmer** [comment]
I double checked that `<link>`s do not need to be closed for rasterizeHTML.js. One example is http://cburgmer.github.io/rasterizeHTML.js/, you can see the page renders itself nicely, while it has a non-closing link.

To me it seems the issue is more complicated than that.

My suggestion would be to start from a minimal HTML document that works, and keep adding your features until it breaks.
