### ISSUE TITLE
No ../dist/rasterizeHTML.allinone.js

### ISSUE THREAD

**Issue by sogen** [cburgmer/rasterizeHTML.js#101]
FYI, there's no file ../dist/rasterizeHTML.allinone.js, 
also there's no dist folder
not found in latest release, also not found in the master.

**Comment by cburgmer** [comment]
Hey, the file only exists in the npm package.

$ npm install rasterizehtml
$ ls node_modules/rasterizehtml/dist/rasterizeHTML.allinone.js

I don't want to check an artefact into Git. If you want to generate it, run `npm test`.

**Comment by sogen** [comment]
Thanks, just noticed it was stated in the Readme.
Got it, it's working :+1:

**Comment by cburgmer** [comment]
Nice
