### ISSUE TITLE
DOMParser errors are not reported to the user.

### ISSUE THREAD

**Issue by SamHasler** [cburgmer/rasterizeHTML.js#102]
DOMParser is here:

https://github.com/cburgmer/rasterizeHTML.js/blob/dd68b6eb97b6446c17a5b1e2d40cbb1430255638/src/browser.js#L219

**Comment by SamHasler** [comment]
non-reporting must be in CSSCritic not rasterizeHTML

**Comment by cburgmer** [comment]
See https://github.com/cburgmer/csscritic/issues/65
