### ISSUE TITLE
Offsetting in the canvas when snapshoting an image

### ISSUE THREAD

**Issue by fmajet** [cburgmer/rasterizeHTML.js#103]
Hello

Thanks you very much for your library, which is really great.
I have tried to sort out a tricky issue for a long time now.
When snapshoting a div with an image embedded it always create an offset in the canvas on left an top.
Here is an example
http://www.hotfootballteams.com/wp-content/themes/sporty/index.html
I tried a lot of fix but without success
Thank you for your help.

**Comment by cburgmer** [comment]
Apologies for the late reply. It looks like this is the issue #78. You should be able to force padding/margin `0` for html and body, and remove the offset. Let me know if that solves your issue.

**Comment by fmajet** [comment]
Thanks you very much for feeckback.
I had already noticed this fix but unfortunately setting padding and margin to 0 did not work for me.
What is strange is inside the div i try to snapshot, only the <img> is offsetted in the canvas, all other HTML elements seem to be at the right place.

**Comment by cburgmer** [comment]
After digging in a bit deeper it looks like your margin/padding are set on the head of the document, but you are only passing the inner div into rasterizeHTML. If you move the style into the div it should work.

**Comment by fmajet** [comment]
A big thank you, that fixs it indeed and also some image rendering issues linked to the same thing.
I did not see any paypal gift link on your wordpress site but i would happpy to contribute if you have or put something in place

**Comment by cburgmer** [comment]
No worries, happy to help :)
