### ISSUE TITLE
webpack require prompt `cssMediaQuery` and `sanedomparsererror ` not found

### ISSUE THREAD

**Issue by QingWei-Li** [cburgmer/rasterizeHTML.js#106]
excuse me,
When I require rasterizeHTML, it did not work normally... what should i do?
```javascript
import RasterizeHTML from 'rasterizeHTML';
```

```
./~/rasterizeHTML/dist/rasterizeHTML.js
Module not found: Error: Cannot resolve module 'cssMediaQuery'
...
.../node_modules/cssMediaQuery doesn't exist...
...
./~/rasterizeHTML/dist/rasterizeHTML.js
Module not found: Error: Cannot resolve module 'sanedomparsererror'
```

**Comment by cburgmer** [comment]
Hey, I haven't used webpack before, so I can only guess for now.

The AMD require's in the header of dist/rasterizehtml.js (line 7) requires `cssMediaQuery` and `sanedomparsererror` although the module names on npm are `css-mediaquery` and `sane-domparser-error`. 

Can you for now try changing the two references and see if it works? We can then commit the change here.

**Comment by cburgmer** [comment]
See my commit efa689f97b4c75d059574720126f2cebdc1102c0 in branch issue106

**Comment by QingWei-Li** [comment]
Like it? It works.

```javascript
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define(["url","css-mediaquery","xmlserializer","sane-domparser-error","ayepromise","inlineresources"], function (a0,b1,c2,d3,e4,f5) {
      return (root['rasterizeHTML'] = factory(a0,b1,c2,d3,e4,f5));
    });
```

**Comment by cburgmer** [comment]
Ok, thanks for checking! I'll merge this into master and will probably make a new release. I hope this doesn't break any existing installations though. Will aim at a minor version bump.

**Comment by QingWei-Li** [comment]
ok, thanks you help

**Comment by fractalawareness** [comment]
I've just trired using this module with webpack and got this issue:
```ReferenceError: window is not defined
    at C:\test\node_modules\rasterizehtml\dist\rasterizeHTML.js:693:38
    at module (C:\test\node_modules\rasterizehtml\dist\rasterizeHTML.js:15:22)
    at Object.<anonymous> (C:\test\node_modules\rasterizehtml\dist\rasterizeHTML.js:19:2)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by cburgmer** [comment]
This library uses a fairly standard UMD header, provided by grunt-umd. This ensures that node- and AMD-style require is supported, and a fallback to global window object is provided. 
I'm assuming that webpack should be able to handle this. I am not a webpack user myself, so I can't verify this, sorry.

**Comment by fractalawareness** [comment]
Thank you for the fast response. Seems like my issue may be related to https://github.com/webpack/webpack/issues/5381

**Comment by fractalawareness** [comment]
Thank you for the fast response. Seems like my issue may be related to https://github.com/webpack/webpack/issues/6642
