### ISSUE TITLE
Could you create example with options usage?

### ISSUE THREAD

**Issue by dadmor** [cburgmer/rasterizeHTML.js#114]
As a subject, thanks.

**Comment by cburgmer** [comment]
Hey, here are some:
- https://github.com/cburgmer/rasterizeHTML.js/tree/master/examples
- https://github.com/cburgmer/rasterizeHTML.js/wiki/Examples
- https://github.com/cburgmer/csscritic/blob/master/src/browser/browserRenderer.js#L29

All available options are described in https://github.com/cburgmer/rasterizeHTML.js/wiki/API.

Are you missing anything in particular?

**Comment by dadmor** [comment]
:) Thanks cburgmer.
Wyniki wyszukiwania

I tried use "then(function (renderResult){}" event to print page body. My site have 1200px width but returned "renderResult" object have inside SVG with width="345" size.  How can I change svg size to 1200px ?

**Comment by cburgmer** [comment]
If you provide a `width` it will override the default size (300px or the width of the canvas if given). This should return an image of the specified width (or greater). See https://github.com/cburgmer/rasterizeHTML.js/wiki/API#optional-parameters.

**Comment by cburgmer** [comment]
Closing this issue for now as it seems there's nothing more to do. Please re-open if needed!
