### ISSUE TITLE
option to disable externalResourcesRequired in rendered svg

### ISSUE THREAD

**Issue by bobsov** [cburgmer/rasterizeHTML.js#115]
i have no external resource in the rendered image, however because of the present of externalResourcesRequired= true, it is giving security exception in Safari and canvas becomes tainted. Should there be an option to enforce externalResourcesRequired = false?

**Comment by cburgmer** [comment]
Hey, as far as I know Safari taints the canvas either way. This might have changed in newer versions (I'm still running something old), let me know if you can reproduce this! 

The line of code that you mentioned has been introduced in hopes of fixing a flaky issue with Safari (https://github.com/cburgmer/rasterizeHTML.js/blame/a4fd22fab74c4625db442fbe1b3c98a6277381b4/src/document2svg.js#L51, see 3. point under https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari).

So the line might not solve the mentioned issue (it's hard to test with flaky results, especially across devices). If it solves your problem, let's remove it. I do want to make sure though that Safari will then not taint the canvas!

**Comment by cburgmer** [comment]
Revisiting this issue it seems that the only pending question here is whether removing said field will bring about any improvement. If so, happy to do that.

**Comment by bobsov** [comment]
This seems to have been fixed in newer version of Safari, and I no longer have this issue.

**Comment by cburgmer** [comment]
Good to hear and Thanks!
