### ISSUE TITLE
background-image not loading

### ISSUE THREAD

**Issue by unclespode** [cburgmer/rasterizeHTML.js#116]
The same URL as an inline image will render, but when as a background-image of a div (set in the style) it won't render. I've tried with the latest built from source.

The offending URL is:

filesystem:http://mydomain.com/temporary/bd1253ebbc8980767e0a8bf0a49210d4b3a3efce

This is obviously on the same domain, using the Chrome FileSystem API.

**Comment by cburgmer** [comment]
Hey, can you verify whether that is 3. under https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#yet-unsupported-html or not? `style="..."` should be easy to support, but so far was never implemented!

**Comment by unclespode** [comment]
Yes, I'm an idiot. I read it as inline ELEMENTS not styles. And I was thinking, "no, this is a block!".

It would be really handy to have this supported. Is there anything I can do to help?

**Comment by cburgmer** [comment]
If you look at the inlineresources package you'll see methods handling the
different ways of style inclusion. Basically we are missing code that looks
for element styles.

**Comment by cburgmer** [comment]
I'll close the issue here, as this belongs to [cburgmer/inlineresources](https://github.com/cburgmer/inlineresources).

This should not be difficult to implement, however it was never required for my own use cases, so it just needs somebody to take on that work :)
