### ISSUE TITLE
No dist/rasterizeHTML.allinone.js vailable in the repo

### ISSUE THREAD

**Issue by grifotv** [cburgmer/rasterizeHTML.js#123]
when checking our and running examples, they don't work straightaway

**Comment by cburgmer** [comment]
Please see #101.
Maybe moving to es6 modules could solve the issue altogether.

**Comment by cburgmer** [comment]
As ES6 has yet to be supported natively I don't see a quick solution here. Closing this for now. Happy to re-open with actionable items.

My goal would be to have the examples in a shape that any user can quickly copy, and so far the "allinone" bundle is the preferred way.
