### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by CedarTree72** [cburgmer/rasterizeHTML.js#126]
Your solution here is exactly what I'm looking for.  On my Wordpress, I called in your script:
`<script src="https://cburgmer.github.io/rasterizeHTML.js/rasterizeHTML.allinone.js">
</script>`

Then, I inserted this on the page:
`<canvas id="canvas" width="100%" height="1000px"></canvas>`

And then...
`<div id="thehtml" style="display: none;">
My HTML is here
</div>`

And then...
`<script>`
`var canvas = document.getElementById("canvas"),`
`html_container = document.getElementById("thehtml"),`
`    html = html_container.innerHTML;`

`rasterizeHTML.drawHTML(html, canvas);`
`</script>``

But all I get is a blank page.  I run this on jsfiddle and it seems to work.  Suggestions?  Thanks!!!

**Comment by cburgmer** [comment]
I'm a bit busy this week, I'll try to get back as quickly as possible,
sorry.

**Comment by cburgmer** [comment]
Can you provide the jsfiddle example?

A first guess: There is an issue with the font size with Chrome and Safari, see https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#webkit-origin, this might affect you.

**Comment by CedarTree72** [comment]
Thanks - I'll play with that.

**Comment by cburgmer** [comment]
Closing for now, if necessary please reopen.
