### ISSUE TITLE
canvas to toDataURL("image/png") not working on ios

### ISSUE THREAD

**Issue by setkyar** [cburgmer/rasterizeHTML.js#136]
First, I try to create an canvas without using rasterizeHTML.js like the following and try to alert **toDataURL("image/png")** that is work fine on ios 9.1 chrome and safari.

```
<canvas id="canvas" width="300" height="200" style="border: 1px solid black;"></canvas>
<script>
var c=document.getElementById("canvas");
var d=c.toDataURL("image/png");
alert(d);
</script>
```

But when I try to use rasterizeHTML.js like the following and try to alert **toDataURL("image/png")** that does not work any more. But the canvas is still appear welll on browser.

```
<canvas id="canvas" width="300" height="200" style="border: 1px solid black;"></canvas>

    <div id="thehtml" style="display:none">
        <p>Hello world</p>
    </div>

       <button id="button">Button</button>

<script>
    var canvas = document.getElementById("canvas"),
        html_container = document.getElementById("thehtml"),
        html = html_container.innerHTML;

      rasterizeHTML.drawHTML(html, canvas); //canvas is ok

         $('#button').click(function() {
        var c=document.getElementById("canvas");
        alert(c); // still arrive to this
        var d=c.toDataURL("image/png"); //never arrive to this.
        alert(d); // this is depend on to DataURL("image/png")
    });
<script>
```

Does any idea?

**Comment by cburgmer** [comment]
Hey, I believe this is the issue with Safari not being able to read back from the canvas (https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari). You should be getting a SecurityError or something related.

**Comment by setkyar** [comment]
Hi @cburgmer , How about chrome? I try with iPhone chrome also but it doesn't work.

**Comment by cburgmer** [comment]
Chrome for iOS seems to be using the same underlying rendering engine as
Safari (UIWebView). And the dev documentation implies that the same
limitations apply.

**Comment by cburgmer** [comment]
I'll close the issue for now, as it seems a current limitation of WebKit is responsible for this behaviour. Sadly there's not much we can do against that (just wait for a fix on their end). Feel free to re-open.
