### ISSUE TITLE
Calculate canvas height dynamically based on passed HTML content

### ISSUE THREAD

**Issue by boo-ga-ga** [cburgmer/rasterizeHTML.js#146]
Hi,
Could anyone tell if it is possible to dynamically create a canvas element with height equal to the height of passed content after it is rendered? I.e. I do not know the height of HTML I'd like to render as it is created dynamically, but would like to have a canvas element which contains all of the content. Then I'm going to convert it toDataUrl and send to server.

**Comment by cburgmer** [comment]
You can get hold of the rendered image, which will always adapt to the necessary size, see https://github.com/cburgmer/rasterizeHTML.js/wiki/API#on-success.
In that case you will need to handle the canvas yourself. However, it seems you are planning to read out the pixel data from the canvas, which will be impossible under Safari, see limitations.

**Comment by boo-ga-ga** [comment]
Yes, that's exactly what I need, thank you! And we do not need to support Safari, so it is fine for our project.

**Comment by cburgmer** [comment]
Closing for now, feel free to reopen.
