### ISSUE TITLE
Issue regarding chrome's csp

### ISSUE THREAD

**Issue by puranjayjain** [cburgmer/rasterizeHTML.js#147]
@cburgmer first of all a really nice project!
Now to the problem: 
I'm trying to use it in an atom package but due to their csp policy I can't seem to generate an image.
I'm getting this error:
`Refused to load the image 'blob:file%3A///0daa8856-e790-486e-9de1-d1c5a3978ae3' because it violates the following Content Security Policy directive: "img-src data: *".`
I see that it is because of blobs being blocked by their csp, 

is their any way we can do it with data urls? 

Any solutions/suggestions?

Thanks you :smiley:

**Comment by cburgmer** [comment]
There is a feature detection toggle that decides whether to go with blobs
or dataURIs. It's there for compatibility reasons with Safari. You can try
forcing one or the other there. Let me know if that helps.

I'll try to give a longer answer once I find more time. My knowledge on CSP
though is rather non existing.

**Comment by puranjayjain** [comment]
@cburgmer how can i force the dataURI feature? it's not mentioned in the api or is there another way?

**Comment by cburgmer** [comment]
For now you would have to dig into the source. I remember there being auto
detection also based on access policies, but that might not work in your
case.

**Comment by puranjayjain** [comment]
@cburgmer thanks!

**Comment by cburgmer** [comment]
Just out of interest, did you manage to fix the problem?

If so, we should keep this issue open so we can provide a proper workaround.

**Comment by puranjayjain** [comment]
Yes the issue seems to be resolved for now. Although I havent had the time to test it on the latest version of Atom. It is safe to assume that it should work here as well. Closing the issue now, will reopen in case of a problem.
