### ISSUE TITLE
position error

### ISSUE THREAD

**Issue by MaxPoon** [cburgmer/rasterizeHTML.js#148]
Hi, I am developing a form builder web app and using rasterizeHTML to convert a div, which is like a page of form, into png using riskihajar's method [https://github.com/cburgmer/rasterizeHTML.js/issues/58]. Everything is fine but I found that the position of the child nodes of the div shift a little bit from their original position as shown below.
Original div contatiner:
![screenshot from 2016-06-04 01 47 21](https://cloud.githubusercontent.com/assets/18631871/15787736/824a664c-29f6-11e6-8fbc-a49c70feb25c.png)
Preview the png in an img tag:
![screenshot from 2016-06-04 01 50 05](https://cloud.githubusercontent.com/assets/18631871/15787767/b11dd954-29f6-11e6-9b69-139be252a723.png)

Initially, I drag the image to the upper-left corner of the parent node (html container). And when I preview the png using an img tag. A small part of the image is out of the background. ( The white background is actually also a child node of the container and have the same size as the container) 

Strangely, after I generate a pdf file using jspdf, the png image looks good in the pdf file:
![screenshot from 2016-06-04 01 56 48](https://cloud.githubusercontent.com/assets/18631871/15787954/a1547626-29f7-11e6-8317-ead19918619d.png)

Any solutions? Thanks!

**Comment by MaxPoon** [comment]
btw, the position of the image is relative

**Comment by cburgmer** [comment]
Sorry for the late reply. Can you verify whether #78 is responsible for that behaviour?

Technically `drawHTML` will always force a full HTML document to be rendered, this includes body margin.

**Comment by cburgmer** [comment]
If this is the case for now you can add a workaround `body { margin: 0; }`.

A new major version of rasterizeHTML will possibly provide two different methods for fragments and whole documents.

**Comment by MaxPoon** [comment]
Hi, I found the reason is that the position background div is relative and the other position of image tag is absolute. It works fine after I add this style to the background div `style="top: -7px; left:-7px; position: absolute"`

Maybe it's a bug that the position of elements will be rendered slightly different when the elements have different position style?

**Comment by MaxPoon** [comment]
Anyway, I have solved my problem. But I encountered another problem that the checkbox, radio button and select cannot be rendered correctly. I will post it as a new issue. Thanks!

**Comment by MaxPoon** [comment]
Anyway, I have solved my problem. But I encountered another problem that the checkbox, radio button and selection cannot be rendered correctly with their values. I will create a new issue.

**Comment by cburgmer** [comment]
Can you provide an example I could look into? 

Alternative guess: the browser's don't treat the html element inside the SVG's foreignObject as a root element, which apparently come with a bunch of properties (similar issue #94). This might be meddling with the absolute positioning. 

Your 7 px are however very close to the 8px that a body by default adds.

**Comment by cburgmer** [comment]
I'll close this for now, pending an example to reproduce. Feel free to re-open!
