### ISSUE TITLE
Security issues toDataURL() (solved?)

### ISSUE THREAD

**Issue by inchl** [cburgmer/rasterizeHTML.js#150]
I want to convert html to an imagebase64 by using the toDataURL() method. Using this component I ran into security issues but when using a similar component found on https://html2canvas.hertzen.com/ these security issues don't occur. Why????

Thanks for any feedback

**Comment by cburgmer** [comment]
Hey, I haven't really looked into html2canvas. As far as I know it interprets HTML itself and uses an elaborate rendering mechanism to replicate browser behaviour.
rasterizeHTML takes a crude approach, and inlines everything into an SVG, which is a valid image the browser can render to the canvas. However, some browsers have issues with their own sandboxing implementation, which is supposed to guarantee that anything user related (e.g. visited page information from `a:visited`) is not leaked. 
However, Chrome and Firefox nowadays should be working fine. Last time I checked Safari still had problems though: https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari

**Comment by inchl** [comment]
That's what I thought. I tried to use this library because its much faster, however it runs into security issues on the canvas image retrieval. Still hoping this could be solved, but I dout it....
Will check for any updates with great interrest!

Stephan

**Comment by cburgmer** [comment]
In case you are still interested in trying to work out the issue, could you provide an example and details on the browser you are using?

**Comment by cburgmer** [comment]
Closing for now, pending more feedback. Feel free to open again!
