### ISSUE TITLE
Checkbox, radio button and selection cannot be rendered correctly with their values

### ISSUE THREAD

**Issue by MaxPoon** [cburgmer/rasterizeHTML.js#151]
I need to dynamically create some checkbox, radio button and select elements by javascript and render the html. But the elements are not rendered with their actual value. See the example here: [fiddle](http://jsfiddle.net/maxpoon/2g1wsoz0/3/)

Is there any workaround? Thanks.

**Comment by cburgmer** [comment]
Can you have a look at #76 and see whether it's the same issue? If I
remember correctly it's just a missing "feature" on the library's side.

**Comment by MaxPoon** [comment]
Hi, I think it's the same issue. I set the checkbox checked by `checkboxElement.checked = true;` , and I just solve the problem by adding this `(if checkboxElement.checked) checkboxElement.setAttribute("checked", "");` 

Similarly you can setAttribute for the input text field, select element or radio button to get them rendered correctly.

**Comment by cburgmer** [comment]
For the time being you can maybe use the workaround as described in #76. This behaviour should be the default in rasterizeHTML though.

**Comment by cburgmer** [comment]
I'll close this issue for now, as we can track this in #76. I'm still in favour of making this an actual feature of the library. Let me know if there's anything left open.
