### ISSUE TITLE
use vanilla browser Promise (ES6)

### ISSUE THREAD

**Issue by gre** [cburgmer/rasterizeHTML.js#154]
(and let user polyfill it if they need to support older browser (that I don't believe they do if they use the library anyway^^))

**Comment by gre** [comment]
N.B. I got bitten by this when doing: `rasterizeHtml.drawHTML(...).then().catch()`

catch not defined

**Comment by cburgmer** [comment]
Good point. Promises seem to be in all the browsers we want to address, users can polyfill if necessary. We can also drop one dependency.
Pull request welcome.

For now `fail` should work, or alternatively `.then(null, function () {})`.

**Comment by gre** [comment]
quick way I found was:

```
Promise.resolve()
.then(() => doTheRasterizeCalls())
...
.catch(...)
```

**Comment by cburgmer** [comment]
This should be solved, but I'll keep this issue open as a reminder to wait for a release of inlineresources which should get rid of the transitive dependency on ayepromise for good.

**Comment by cburgmer** [comment]
Released in https://github.com/cburgmer/inlineresources/releases/tag/0.4.0, dependency bumped in 1d032acae5, needs release.

**Comment by cburgmer** [comment]
Released.
