### ISSUE TITLE
Issue with svg and defining an image.

### ISSUE THREAD

**Issue by PyuuCH** [cburgmer/rasterizeHTML.js#157]
Essentially, my issue is that: `<defs>
        <pattern id="image" patternUnits="userSpaceOnUse" height="512" width="512">
            <image x="0" y="0" height="512" width="512" xlink:href="anything.png"></image>
        </pattern>
    </defs>` results in a white screen being rendered, regardless of image, location, or anything. It also does the same when referring to external locations, such as http://blah.com/image.png.

Checking the networking in Chrome, the image is being loaded successfully, along with the html and things of the sort. No errors are reported by rasterize.js.

I know rasterizeHTML supports the SVG format in html files. I can get lots of things to work with it and render properly. The only exception is when `xlink:href="anything.png"` is involved. I can exclude that part of the <image> tag and everything will render fine except for the image.

Unfortunately, I can't upload the files I use to this issue because "We don't support that file type." (even when I try with a zip.) So I'll just link it instead: https://dl.dropboxusercontent.com/u/76573586/Files.zip

**Comment by cburgmer** [comment]
This might just need another release. If you check https://github.com/cburgmer/inlineresources/compare/0.2.0...master there is a fix for svn image for the downstream dependency. However as far as I can see the current version of rasterizeHTML still ships with the older version.

Apologies for the short message, I am a bit busy know. Maybe you can try upgrading manually to check whether that fixes your issue.

**Comment by cburgmer** [comment]
Did you manage to solve the problem?

**Comment by cburgmer** [comment]
Closing for now, pending more feedback. Feel free to re-open.
