### ISSUE TITLE
SVGStyleElement.sheet is undefined on iOS

### ISSUE THREAD

**Issue by akarienta** [cburgmer/rasterizeHTML.js#158]
Hi, I am trying to get this plugin working with Cordova on iOS. It is crashing in function `replaceSimpleSelectorsBy` on [this line](https://github.com/cburgmer/rasterizeHTML.js/blob/ea79622e9c894744effabad7347259797bf2bb03/src/documentUtil.js#L64) because `styleElement.sheet` is undefined for elements with type `SVGStyleElement` on iOS. 

Do you have any idea how to fix it?

**Comment by cburgmer** [comment]
Can you provide a minimal HTML input to help me understand in which context the code is called? I won't be able to reproduce (missing an iOS device) but I'd like to know whether this fails on an inlined stylesheet or whether a stylesheet required via `<link href>` for example.

There are are the other odd open bugs for iOS, you might want to check those to see how feasible overall support is under iOS for using this library (although some of those issues might have been fixed via newer iOS versions).

There are quite a few usages of `sheet.cssRules` in the overall code, some of them in https://github.com/cburgmer/inlineresources, so depending on which HTML you employ, those might also fail you.

If your use case is limited, you might be able to remove some of those invocations, as they only given wrong results in certain cases. (The code you referenced is used in two cases, one for dealing with a side effect from upper case CSS selectors, and two for invoking the :hover effect if selected.)

However let's not give up to early, we might get some ideas looking at the HTML!

**Comment by akarienta** [comment]
It is used in exported icons by AI.

```html
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.2.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="something" xmlns="http://www.w3.org/2000/svg"
	 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 48 48" style="enable-background:new 0 0 48 48;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#000000;}
</style>
	 <path class="st0" d="something"/>
</svg>
```
I've placed some workaround before [that problematic row](https://github.com/cburgmer/rasterizeHTML.js/blob/ea79622e9c894744effabad7347259797bf2bb03/src/documentUtil.js#L64):

```javascript
if (!styleElement.sheet) {
    styleElement.sheet = {
        cssRules: [{selectorText: styleElement.innerHTML.split('{')[0].trim()}]
    }
}
```

It seems in this part of code it works properly now. There is no other run time error, `rasterizeHTML.drawDocument()` promise isn't resolved nor rejected so I guess it is crashing quietly somewhere else.

**Comment by cburgmer** [comment]
I'm not sure about the general form of your images. But the use case above is trivial enough to just be drawn into a canvas directly, if that's what you need (e.g. http://stackoverflow.com/a/3769883/575501).

Your example does work in Firefox and Chrome, but not in my older Safari on OS X. Looks like a Safari issue. Let me see whether there's a known issue.

**Comment by cburgmer** [comment]
For a more permanent workaround - if you desire a proper fix - we could

1. detect a null `sheet` value
2. parse the `textContent` ourselves via e.g. https://github.com/cburgmer/inlineresources/blob/master/src/cssSupport.js#L26

(PR welcome :)

**Comment by cburgmer** [comment]
Just to reproduce with a minimal test case: https://jsfiddle.net/cburgmer/smea222j/1/

The developer console in Chrome reports a parsed rule, while Safari fails for both. 

I did not find any entry in Webkit's bug tracker. If you can still reproduce this issue in a newer Safari, feel free to open a ticket there to have this fixed for good https://bugs.webkit.org/buglist.cgi?quicksearch=style+sheet+null.

For the meantime I've documented this here: https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari

Let me know if this works for you.

**Comment by akarienta** [comment]
> If you can still reproduce this issue in a newer Safari
I can reproduce it in Version 10.0 (11602.1.50.0.10)

Do you think it can cause problems also in other part of code? Because when I fix this issue the app still crashing but there is nothing in error log. Do you have some hints how to continue with debugging?

**Comment by akarienta** [comment]
> Just to reproduce with a minimal test case ...

Thanks for that!

> (PR welcome :)

Done.

> If you can still reproduce this issue in a newer Safari ...

I am able to reproduce it in Safari Version 10.0 (11602.1.50.0.10)

> ... feel free to open a ticket there to have this fixed for good ...

Yeah, I will do.

**Comment by akarienta** [comment]
Fixed in #159.

**Comment by cburgmer** [comment]
Thanks!

I moved the description of the issue to https://github.com/cburgmer/rasterizeHTML.js/wiki/Browser-issues#safari, which is a reference for everything that's either been a browser bug or still is, but has been worked around here. (Contrary to outstanding issues listed under https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations.)

I'm tracking the list of unrelated outstanding issues in #160, I'll try to make a release, once this is done.

**Comment by Ahmad-S792** [comment]
Just to add this issue is now fixed in Safari Technical Preview 151.
