### ISSUE TITLE
Please publish 1.2.3 to NPM

### ISSUE THREAD

**Issue by DinkDonk** [cburgmer/rasterizeHTML.js#161]
Thanks for the updates on the project. Really appreciate it!

Could I ask you to publish the latest tag to NPM?
I would gladly do it, but I don't have permission 😄

**Comment by cburgmer** [comment]
Apologies, I've tried building and uploading from a clean Vagrant box (the
one in the project's root). However npm is currently getting stuck on my
Internet connection. I'll try again later.

A clean build is important to me because of the deps included in the
all-in-one build.

**Comment by cburgmer** [comment]
npm crashed on the 500MB box with an out of memory error.

Also I had to switch to Google's nameserver, as npm would otherwise stall for long periods, which was the harder part to find out.

Package should be up now.
