### ISSUE TITLE
Working with jsPDF

### ISSUE THREAD

**Issue by noopole** [cburgmer/rasterizeHTML.js#162]
I'd like to integrate a HTML table in a PDF document with jsPDF.

I can create a image with `rasterizeHTML.drawHTML( html )`, and I can put my image in a `<canvas>` or insert it in the DOM as an `<svg>` element. 

The SVG image is perfect, but the Canvas is pixelized and the table borders are lost.

I ~~can't~~ can insert it in a jsPDF document using canvas's `toDataURL()` method. 
Can I do the same with the SVG?

**Comment by cburgmer** [comment]
Looking at e.g. http://stackoverflow.com/questions/5913338/embedding-svg-in-pdf-exporting-svg-to-pdf-using-js tells me that SVGs cannot be embedded into PDFs, but need translation into the PDF syntax.

As for the pixelated rasterized version, you can try using a canvas twice the size, and then scaling the resulting image back down, when you insert the bitmap into the PDF.

> I can't insert it in a jsPDF document using canvas's toDataURL() method. 

`toDataURL()` should give you a PNG under Firefox and Chrome (not on Safari sadly, AFAIK, see https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari). Can you clarify what's not working as expected?

> Can I do the same with the SVG?

Can you clarify what you mean?

**Comment by noopole** [comment]
Sorry I made a mistake in the first statement you quoted. Maybe the correction will also clarify the question.

I want to insert the SVG with the right CSS styles and border (which I cannot get from the Canvas).
And I would like to be able to zoom in the  PDF without loss. As you stated it needs a SVG-to-PDF "translation", but I thought it was included in jsPDF, because it seems to work (partially) with html2canvas.

**Comment by noopole** [comment]
Finally I will use scaled PNG and JPEG images to insert in the jsPDF document. It works wery well. 
No need for SVG.
