### ISSUE TITLE
Using rasterizeHTML.drawHTML into ionic angularjs

### ISSUE THREAD

**Issue by lucav90** [cburgmer/rasterizeHTML.js#172]
Hi,

i want to use your function rasterizeHTML.drawHTML into my ionic / angular app.

I've tried but i have the error: Unknown chromium error: 0 

It's possibile to solve this?

Regards,

**Comment by cburgmer** [comment]
Hey, this is not enough info for me to start reproducing this. Could you setup a simple jsfiddle.net or equivalent which shows what you are trying to do? You can source the library from https://cdnjs.com/libraries/rasterizehtml if necessary.

Independently, you should try getting hold of the `.then()` handler as described in the [API](https://github.com/cburgmer/rasterizeHTML.js/wiki/API#return-value). This way you can be notified about internal errors.

**Comment by cburgmer** [comment]
Closing this for now. If you have more information fell free to reopen!
