### ISSUE TITLE
No main in the package.json

### ISSUE THREAD

**Issue by lonelydatum** [cburgmer/rasterizeHTML.js#174]
Should there be a main in the package.json like this?

"main": "./dist/rasterizeHTML.min.js",

I"m getting an error when running Jest unit test 
 Cannot find module 'rasterizehtml' from

After adding the main in the package.json the error went away. Am I consuming the package wrong for the test?

**Comment by cburgmer** [comment]
Good point. There is an entry for browserify (`"browser": "dist/rasterizeHTML.js"`) but I believe for other packaging methods a "main" entry could be used instead. We should include that!

**Comment by cburgmer** [comment]
#54 just for the record documents my initial reasoning.
