### ISSUE TITLE
@font-face triggers a new download for each generation.

### ISSUE THREAD

**Issue by Nehon** [cburgmer/rasterizeHTML.js#177]
Hello, we are using rasterizeHTML to make 3D guis.
The idea is to have html templates of the uis and generate them as textures with rasterizeHTML and use them in a 3D viewer. It's working great so far but we've hit an issue that is killing the performance.

We use font-awesome for icons and Open Sans as a font using @font-face css markers.
It works, but the assets (css + woff+ ttf... etc files) are downloaded each time we generate a texture.
We have some screens where 20 textures can be generated, and it's killing the perfs.

I'm using a common cache bucket for all the generated texture like this : 
```
.drawHTML( element, canvas, {
                cacheBucket: cacheBucket,
                cache: 'all'
            } )
```
cacheBucket is a global empty object, and I can see that some cache data are set and reused with each generation. however it still downloads the font files.
I don't know if this issue is also happening with other types of external assets like images, I don't have the case, but it could be.

I worked around the issue by embedding svg data in the CSS for font awesome icons (not all of them only the ones I use) and I've also embedded Open Sans as base64 data in the CSS and it's working well and fast.

But I was wondering if there could be a way to have rasterizeHTML hit the cache to only download the files at the first generation and use the cache for subsequent generations.

**Comment by Nehon** [comment]
After more testing it seems that it's not a cache issue... the file is actually fetched from memory... Though I have a huge decrease in performance when I link the font to the font files compared to embedding it as base64 data...
I have to clear that up maybe I'm doing something wrong. I'll post another issue if ever I have something more tangible and that it's related to rasterizeHTML

**Comment by cburgmer** [comment]
Interesting find! It is possible that the embedding process itself takes some time. You could try profiling the code around https://github.com/cburgmer/inlineresources/blob/master/src/inlineCss.js#L273 to see where the time is spent.

Feel free to re-open with more details.
