### ISSUE TITLE
does not render correctly (– parent svg element too big?)

### ISSUE THREAD

**Issue by freder** [cburgmer/rasterizeHTML.js#178]
hi,

I'm having problems getting things to render correctly:

![screen-shot-2017-03-09-at-17 26 20](https://cloud.githubusercontent.com/assets/724844/23760171/3447deb4-04ef-11e7-8d4a-cb8a5dc04c50.png)

**left:** canvas output
**right:** rasterizehtml svg

as you can see, the svg that rasterizehtml creates is 100px bigger in height and width than the element I am rendering. – and I suspect that's the reason things don't render as expected.

I wonder why that is, and if there is a way to fix it.

**Comment by cburgmer** [comment]
That looks interesting, can you provide the input/HTML? I'm guessing that the html/body element margin/padding might add to that, but let's see first.

**Comment by freder** [comment]
input html:

```html
<div id="Leaflet" style="width: 620px; height: 874px; background-position: center top; background-repeat: no-repeat; background-size: cover; padding: 50px; font-family: &quot;GT America Trial&quot;, serif; font-weight: 500; display: flex; flex-direction: column; justify-content: space-between; z-index: 99999; position: absolute; top: 0px; right: 0px;">
    <div>
        <div id="header" style="text-align: center; margin-bottom: 50px; font-size: 60px;">HEADER</div>
        <div id="text" style="font-size: 24px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, temporibus maxime aperiam odit! Dolorem suscipit exercitationem deleniti temporibus et officia dolor, libero ipsum qui corrupti cumque reprehenderit, at dolores, quia!</div>
    </div>
    <div>
        <div id="footer" style="text-align: center; margin-bottom: 50px;font-size: 60px;">FOOTER</div>
        <div id="meta" style="text-align: center; font-size: 12px;">etc.</div>
    </div>
</div>

```

generated svg:

```html
<svg xmlns="http://www.w3.org/2000/svg" width="720" height="974" font-size="16px" style="z-index: 99999; position: absolute; top: 0px; right: 0px;">
	<style scoped="">
	html::-webkit-scrollbar {
		display: none;
	}
	</style>
	<foreignObject x="0" y="0" width="720" height="974" style="float: left;" externalresourcesrequired="true">
		<style>
		html, body {
			padding: 0px;
			margin: 0px;
		}
		</style>
		<div id="Leaflet" style="width: 620px; height: 874px; background-position: center top; background-repeat: no-repeat; background-size: cover; padding: 50px; font-family: &quot;GT America Trial&quot;, serif; font-weight: 500; display: flex; flex-direction: column; justify-content: space-between;">
			<div>
				<div id="header" style="text-align: center; margin-bottom: 50px; font-size: 60px;">HEADER</div>
				<div id="text" style="font-size: 24px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, temporibus maxime aperiam odit! Dolorem suscipit exercitationem deleniti temporibus et officia dolor, libero ipsum qui corrupti cumque reprehenderit, at dolores, quia!</div>
			</div>
			<div>
				<div id="footer" style="text-align: center; margin-bottom: 50px; font-size: 60px;">FOOTER</div>
				<div id="meta" style="text-align: center; font-size: 12px;">etc.</div>
			</div>
		</div>
	</foreignObject>
</svg>
```

a thing I noticed is that quotation marks are getting converted to html entities (`font-family: &quot;GT America Trial&quot;, serif;`) — that's s.th. I need to fix in my code, but that's probably also not the actual problem here.

also I am using the trick described in https://github.com/cburgmer/rasterizeHTML.js/issues/78#issuecomment-235138076 to get rid of any extra padding / margin.

**Comment by cburgmer** [comment]
Sorry for the late answer.

I have a few issues reproducing your issue exactly, it is late here, I might be missing things:

1. You haven't specified the size of your canvas. Assuming 620px (same as the HTML), I cannot reproduce the left image, as the content is 620px + 2*50px wide, and aligned to the right means, that it overflows to the left (and not to the right as your image suggests).
2. The right image from the SVG is wrong in my eyes, as you defined a width of 620px + a padding of 50px. It looks as if a `box-sizing: border-box` slipped in with the rest?

**Comment by freder** [comment]
you are absolutely right: there was indeed a `* { box-sizing: border-box }` that I didn't think of. — thanks so much!
