### ISSUE TITLE
picture can not render.

### ISSUE THREAD

**Issue by phypor** [cburgmer/rasterizeHTML.js#181]
code http://jsfiddle.net/E8fb2/588/

**Comment by francoisromain** [comment]
Maybe this is due to the same origin limitation: https://github.com/cburgmer/rasterizeHTML.js#limitations

**Comment by cburgmer** [comment]
Sorry for the late response, and thanks for the simple example! To me it looks good now in Firefox, at least I see one image loaded and the CORS headers are set by the server. I'm assuming you found a fix?

**Comment by cburgmer** [comment]
Closing for now, feel free to reopen with more information.
