### ISSUE TITLE
Provide TS definitions

### ISSUE THREAD

**Issue by atrauzzi** [cburgmer/rasterizeHTML.js#184]
Interested in seeing TS definitions added to the DefinitelyTyped repository for this library! 😄

**Comment by cburgmer** [comment]
Generally open to that, but not using TypeScript enough to be able to contribute.

**Comment by orentrutner** [comment]
@cburgmer, would you consider a code contribution? I'll submit a PR with bundled types, which means a rasterizeHTML.d.ts included in the dist/ folder. I believe DefinitelyTyped prefers that. Alternatively, if you prefer not to add the types directly, I can submit to DefinitelyTyped -- but will defer to you in case you prefer to own the typings file.

**Comment by cburgmer** [comment]
Changes merged, one more reason to prepare for a new release. I'll try to document what's currently blocking in #189
