### ISSUE TITLE
RasterizeHtml with jsPlumb

### ISSUE THREAD

**Issue by luvicri** [cburgmer/rasterizeHTML.js#185]
Hi, i'm using jsPlumb to build a graph, jsPlumb uses svg to create the links between the nodes, but when i lunch drawHtml in the rendering result there aren't the links! How can i solve the problem? 
Best regards.

**Comment by cburgmer** [comment]
Hey, sorry for the late answer. I don't know jsPlumb. Probably the best way to narrow down the problem is to get hold of a minimal generated svg and start from there. Can you provide a simple graph?

**Comment by cburgmer** [comment]
Closing for now, please reopen with more information if needed.
