### ISSUE TITLE
rendered image is 4px off

### ISSUE THREAD

**Issue by sixinli** [cburgmer/rasterizeHTML.js#187]
in `calculateContentSize` it uses the iframe's `scrollWidth`/`clientWidth` and `scrollHeight`/`clientHeight` to detect the size of viewport. however, user agent by default has `border-width: 2px` on `iframe` 
<img width="404" alt="screen shot 2017-06-07 at 4 52 55 am" src="https://user-images.githubusercontent.com/4587468/26870250-63ee758a-4b3d-11e7-8321-326a383b39ef.png">

and thus causing the iframe's `scrollWidth`/`clientWidth`/`scrollHeight`/`clientHeight` to be `4px` smaller than the actual set width.
<img width="327" alt="screen shot 2017-06-07 at 4 56 46 am" src="https://user-images.githubusercontent.com/4587468/26870362-be3699d2-4b3d-11e7-866c-dc0c3fcad4fe.png">

we can fix this by adding `border: none` to the iframe

**Comment by cburgmer** [comment]
Do you have a minimal HTML example to show the effect? It would help me understand the impact and maybe even craft a test from that.

**Comment by sixinli** [comment]
realized that this is a combination of `border-width` + `box-sizing: border-box`, fiddle in: http://jsfiddle.net/s82oonds/1/ (notice that the svg has size 200px * 300px, and foreignObject has size 196px * 296px

**Comment by cburgmer** [comment]
Thanks. Good find!

Here's an even smaller example to reproduce: http://jsfiddle.net/cburgmer/s82oonds/2/

And here's an example I'd like to use to explain this: https://jsfiddle.net/cburgmer/h0nydubw/

rasterizehtml.js tries to measure the content's viewport by rendering the whole thing in an iframe embedded in the caller's page. The iframe get's the specific initial width as given by either the canvas or optionally a width parameter to mimic the available viewport area. 
If the parent page now sets a different box-sizing to the iframe, then this leaks into the inner width of the iframe.
