### ISSUE TITLE
Issues while Rendering and unable to (.then)

### ISSUE THREAD

**Issue by VasucharyBonthi** [cburgmer/rasterizeHTML.js#190]
1. Unable to use then ( rasterizeHTML.drawHTML(html).then ) it showing error i have attached screenshots for your reference 
2. i am unable to load fonts while converting div to canvas 
3.. in canvas there is default scroll bars are rendering 
 
![image](https://user-images.githubusercontent.com/7251202/27439955-e47369f4-5786-11e7-965a-013a0c753215.png)

**Comment by cburgmer** [comment]
Can you provide the version of the library, and if it's installed via npm, which version of `inlineresources` you are using?
Also, if you are using the bleeding edge version, then it would help to know whether you are using a particular promise library.
Sharing a minimal example on jsfiddle or similar will allow me to look into the issue directly.

**Comment by cburgmer** [comment]
Closing until provided more details. Feel free to reopen then.
