### ISSUE TITLE
how is it differ from dom-to-image?

### ISSUE THREAD

**Issue by hbakhtiyor** [cburgmer/rasterizeHTML.js#191]
https://github.com/tsayen/dom-to-image

**Comment by alanhg** [comment]
@hbakhtiyor https://github.com/tsayen/dom-to-image/pull/119

**Comment by cburgmer** [comment]
Wasn't on my radar so far, seems younger than this project.

Happy for somebody to write down a more in-depth comparison. Until then, let's close the issue.
