### ISSUE TITLE
Add coordinate in options?

### ISSUE THREAD

**Issue by chitgoks** [cburgmer/rasterizeHTML.js#193]
More like a feature request. rasterize html string in a canvas of width and height at coordinate x,y

**Comment by cburgmer** [comment]
I'll try a longer answer later. For now:

The API wiki page explains how to achieve this behaviour with a little bit more code.

**Comment by cburgmer** [comment]
Sorry, here's a good example: https://github.com/cburgmer/rasterizeHTML.js/wiki/Examples#putting-the-html-on-the-canvas-ourselves.

**Comment by chitgoks** [comment]
hi chris. i saw this, thank you very much
