### ISSUE TITLE
Does this module inline styles set by <style> tags?

### ISSUE THREAD

**Issue by kylesimmonds** [cburgmer/rasterizeHTML.js#195]
I'm using this plugin on a page created with React, using style tags in the `<head>` like:

```
<style type="text/css">
body {
  font-family: serif;
  color: red;
}
</style>
```

where the HTML would be something like:

```
<h1>Hello</h1>
<p>Body copy</p>
```

The actual HTML renders as I expected in a canvas, but it doesn't pull the styles that are set as style tags. So my question is, does this module account for `<style>` tags in the document, or is that a limitation of this module that I missed on the [limitations page?](https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations)

**Comment by cburgmer** [comment]
The style you want to apply needs to be included in the content passed to either of the methods. The parent page from which you call rasterizeHTML is not supposed to have any impact on what's being rendered. Does that explain your question?

**Comment by kylesimmonds** [comment]
@cburgmer I think so. So you're saying that if I call `.drawHTML()` on a `div`, it has to have the style tag within that `div`? If that's the case that makes sense, and I'll try a test with the `style` tag inside the `div`

**Comment by kylesimmonds** [comment]
@cburgmer I ran the test with adding the style tag to the HTML to be rendered, and I can confirm that it works as expected that way. Thanks!
