### ISSUE TITLE
set options which is not effective

### ISSUE THREAD

**Issue by lgyytm** [cburgmer/rasterizeHTML.js#196]
`rasterizeHTML.drawDocument(dom,canvas,{width: dom.clientWidth, height: dom.clientHeight})`
dom is what I want to render,and it's 1920 px width and 1080px height
then I got the canvas with 300 px's width and 150 px's height

**Comment by cburgmer** [comment]
I've created a basic example, which we can try to use to reproduce the issue you are having. 
https://jsfiddle.net/akdtqye2/1/

In the current setup the `dom` hasn't been rendered yet by the browser, so no clientWidth or height are available.

Can you try to extend the example so we can see what's going on?

**Comment by cburgmer** [comment]
I'll close this until provided with more information. Feel free to reopen then.
