### ISSUE TITLE
Updated npm package?

### ISSUE THREAD

**Issue by rsuk** [cburgmer/rasterizeHTML.js#199]
Is there an updated version of the npm package available anywhere? The current npm package seems to be significantly different from the current github source.

Maybe related, but I had to change the mootools version on the jsfiddles on https://github.com/cburgmer/rasterizeHTML.js/wiki/Examples to Mootools 1.6.0 to get them to work.

**Comment by cburgmer** [comment]
Will try to find some time for that. Closing in favour of #189
