### ISSUE TITLE
CSS is ignored when rasterizing a DOM element

### ISSUE THREAD

**Issue by RemiV2** [cburgmer/rasterizeHTML.js#200]
Hello! I'm trying to render a single `div` from the DOM using the following code:  
```javascript
const element = document.querySelector(".toRasterize"); rasterizeHTML.drawDocument(element, canvas)
```
But the canvas created has no styling. However, when I render the entire document using `rasterizeHTML.drawDocument(document, canvas)`, everything works fine.  

Is there something I'm missing here?

**Comment by RemiV2** [comment]
Here's a solution I found in case someone else has this problem. The CSS is ignored, but inline styles are applied, so I moved all my element's style from CSS to inline.  
I used the npm package [computed-style-to-inline](https://www.npmjs.com/package/computed-style-to-inline-style) to do so, but you could do it manually using `getComputedStyle`.  
Feel free to close this issue !

**Comment by cburgmer** [comment]
Your observations are correct. This is on purpose. Only the given element with children will be rendered, styles apply to this rules as well.

**Comment by zardaloop** [comment]
HI @remi2j ,
Could you please give an idea of how you wrote your code to solve this issue? 
I am trying to do this but I am getting nowhere with it. 
var source = $('.fc-view-container')[0];
computedStyleToInlineStyle(source);
var elemet = source.innerHTML;
var canvas = document.createElement("canvas");
rasterizeHTML.drawHTML(elemet,canvas).then(function (renderResult) {            
            var imgData = canvas.toDataURL();                  
            doc.addImage(imgData, 'JPEG', 0,0);
            doc.save("data.pdf");
        });

**Comment by cburgmer** [comment]
Hey @zardaloop, the idea of this API is to render everything from the given node on, *not* anything that's outside of that. So if you render `document` itself, everything will already be included, however if you render an element somewhere below the tree, then you might have CSS that's outside of that. Does this make sense?

**Comment by zardaloop** [comment]
Yes @cburgmer , it makes perfect sense. And also many thanks for getting back to me so quick. Thanks

**Comment by zardaloop** [comment]
@cburgmer  so one more question on this issue, when I use drawDocument, it looks like is replacing what is appearing on the screen, do you know what I am doing wrong? Thanks

**Comment by cburgmer** [comment]
Hey, sorry for the late reply. `drawDocument` is manipulating the document that you pass in. That API was never meant to be used on the current document, but sadly this is not well documented.

**Comment by zardaloop** [comment]
I see, thanks for getting back to me. I was hoping to maybe clone the document and pass that on o the function but I had no luck with that either.

**Comment by cburgmer** [comment]
I've never tried implementing that, but my hope was that using `cloneNode()` (https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) could provide that.
