### ISSUE TITLE
Cant convert SVG to Canvas

### ISSUE THREAD

**Issue by tifDev** [cburgmer/rasterizeHTML.js#206]
Here is a fiddle https://jsfiddle.net/ux4tj0ys/1/

It doesnt render the SVG on canvas

**Comment by cburgmer** [comment]
Hi, the error here is that you need to use the all-in-one bundle if you don't want to specify all dependencies yourself, and select the whole SVG as well: https://jsfiddle.net/ux4tj0ys/2/. Hope this helps.
