### ISSUE TITLE
Difference between rasterize in dev (localhost) and other environments

### ISSUE THREAD

**Issue by pierre-moire** [cburgmer/rasterizeHTML.js#209]
Hi,

Everything is working on my localhost environment although I get some errors. As soon as I deploy my app with a real domain name nothing is working properly anymore. In both cases I use rasterizeHTML.drawDocument.

Localhost
== 
Screenshot of the PDF I get:
![image](https://user-images.githubusercontent.com/2143238/78977482-7d4f4500-7b18-11ea-9e1c-5125c6d7d3f4.png)

Console:
![image](https://user-images.githubusercontent.com/2143238/78977527-8c35f780-7b18-11ea-858f-d90de518740a.png)

Deployed version
==
Screenshot of the PDF I get:
![image](https://user-images.githubusercontent.com/2143238/78977727-ea62da80-7b18-11ea-9f6a-3903b42cae02.png)

Rasterize.errors : []

Console:
![image](https://user-images.githubusercontent.com/2143238/78977803-08303f80-7b19-11ea-8acd-fca74d352e42.png)

Do you have already encountered this behavior? Any clue of what is producing this and how I can fix it?

Many thanks

**Comment by cburgmer** [comment]
The sandbox warnings/errors should not be of concern, as this is part of the library's execution model.

I'm probably missing a lot of context, but what you could try is to see whether all the depending resources could be loaded by the library. Have a look at the network tab and see whether there are any errors when loading CSS, images or JavaScript files. My concern here is that maybe in production you have cross origin issues that you wouldn't normally find when testing locally.

**Comment by pierre-moire** [comment]
Thanks for your reply :)

I checked the network on both dev and prod and saw no error at all:

Dev:
![image](https://user-images.githubusercontent.com/2143238/79426779-ed9c1180-7fc3-11ea-9380-444e9144705b.png)

Prod:
![image](https://user-images.githubusercontent.com/2143238/79426659-be85a000-7fc3-11ea-8417-ace15db8870a.png)

**Comment by pierre-moire** [comment]
I checked again and found that the differences come from missing class names on elements. Both divs and svg elements are missing some css classes.

It seams that emotion / css in js is not working too well. Everywhere I used normal jsx it works. and everywhere I use styled divs with emotion / css in js it doesnt work
