### ISSUE TITLE
jsFiddle appear outdated

### ISSUE THREAD

**Issue by JirkaDellOro** [cburgmer/rasterizeHTML.js#213]
Browser shows these error messages:

Loading failed for the <script> with source “http://cburgmer.github.com/rasterizeHTML.js/rasterizeHTML.allinone.js”.

**Comment by cburgmer** [comment]
Thanks for reporting. I assume you are referring to https://github.com/cburgmer/rasterizeHTML.js/wiki/Examples.

Github deactivated the older URLs to project sites this summer which seems to have affected the examples.

I have now fixed the JS references. Please re-open if there's any other issue!
