### ISSUE TITLE
Doesn't work as CDN

### ISSUE THREAD

**Issue by chladnefazole** [cburgmer/rasterizeHTML.js#222]
Hello, I'm trying to use this package without NPM. I tried several CDNs from unpkg, cdnpkg, jsdelivr, etc.

I always get this error (v1.3.0 works fine, and it looks like the problem is in the inlineresources dependency which was updated):
![image](https://user-images.githubusercontent.com/28662715/199740144-0ef7cca1-9967-444b-b02c-ba7630fded3c.png)

**Comment by cburgmer** [comment]
It looks like you are using the vanilla version without dependencies included. Try the rasterizeHTML.allinone.js, that should work for you. (`inlineresources` is a dependency that you'd have to provide yourself otherwise.)

**Comment by chladnefazole** [comment]
Aha, thank you!
