### ISSUE TITLE
Webkit fails to render SVGs

### ISSUE THREAD

**Issue by koppor** [cburgmer/rasterizeHTML.js#39]
Including SVGs in the HTML leads to a parsing error. Is it possible to add SVG support?

Example SVG:

    <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
       <circle cx="100" cy="50" r="40" stroke="black" stroke-width="2" fill="red" />
    </svg>

**Comment by sbrown345** [comment]
It looks like this is working in Safari now.

**Comment by cburgmer** [comment]
Thanks, Simon. It also works for me now. Seems WebKit has caught up!

I've updated the docs (https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#webkit-origin), and will close the issue.

As always, happy to reopen if necessary.
