### ISSUE TITLE
Chrome freezes when using rasterizeHTML.drawDocument() on a large page.

### ISSUE THREAD

**Issue by utre** [cburgmer/rasterizeHTML.js#47]
Chrome freezes when using rasterizeHTML.drawDocument() on a large page.  It appears that rasterizeHTML is iterating through a loop too many times.  The following error appears 27 times in the console:

Blocked script execution in 'http://redacted' because the document's frame is sandboxed and the 'allow-scripts' permission is not set. rasterizeHTML.allinone.js:11

The error does not appear in Firefox.  Also, I can confirm that my code is not calling rasterizeHTML.drawDocument in a loop.

Here is my code.

<code>
   function drawPostageStamp(){
      var postageWidth = $('#redacted').width();
      var postageHeight = $('#redacted').height();

      if ($('#postage_stamp').length == 0){

         $('body').append('<canvas id="postage_stamp" width="' + postageWidth + '" height="' + postageHeight + '"></canvas>')

         var postageTopMargin = $('#redacted').offset().top;
         var newPostageWidth = postageWidth * 0.08

         $('#postage_stamp').css({'width':newPostageWidth, "top":postageTopMargin, "right":0, "z-index":10, "position":"fixed"})
         $('body').append('<div id="stamp_bar" style="position:fixed; top:140px; right:0px; width:' + newPostageWidth * .95 + 'px; height:10px; opacity:0.5; background-color:lightblue; z-index:11"></div>')

         $('#stamp_bar').hide();

      };

      var canvas = document.getElementById('postage_stamp');
      var ctx = canvas.getContext('2d');

      //Clear the Canvas
      // Store the current transformation matrix
      ctx.save();
      
      
      // Use the identity matrix while clearing the canvas
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      
      //Restore the transform
      ctx.restore();

      //Set Canvas height (different from css height) of
      //canvas
      $('#postage_stamp').attr('height', postageHeight);

      //Draw the document into the canvas
      setTimeout(function(){
         rasterizeHTML.drawDocument(window.document,canvas,stampInit());
      }, 500);
   };
</code>

Thanks!  I love the library, BTW.  Other than this issue, I haven't had any trouble with it, and the results look amazing!

**Comment by cburgmer** [comment]
Closing this issue for now as we would need more feedback to reproduce. Please re-open if needed!
