### ISSUE TITLE
Unable to call any draw function

### ISSUE THREAD

**Issue by muiro** [cburgmer/rasterizeHTML.js#60]
All calls to draw functions failing with:

Uncaught TypeError: Cannot call method 'inlineReferences' of undefined.

Here is a simple test case I was using that will reproduce the issue:

```
rasterizeHTML.drawHTML("<p>hello world</p>",canvas);
```

**Comment by batiste** [comment]
rasterizeHTML.js necessitate packages such as xmlserializer, sane-domparser-error and inlineresources.

Trying to use the script standalone in a browser without having those script loaded will result in an error. If you are using a CDN version, try to use the `allinone` version that contains everything needed https://cdnjs.com/libraries/rasterizehtml
