### ISSUE TITLE
Rasterize HTML (no images) then toDataURL causing "Tainted canvases may not be exported" exception in Chrome

### ISSUE THREAD

**Issue by pugsley** [cburgmer/rasterizeHTML.js#62]
This modified example attempts to call toDataURL and print it to the console: http://jsfiddle.net/NfE3c/262/

In Chrome (35.0.1916.114) I get the following error:
"Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported."

It works fine in Firefox (29.0.1 & 30.0).

Curiously, this example that doesn't use the rasterizeHTML.js works in Chrome and uses an image. http://jsfiddle.net/handtrix/YvQ5y/

Any ideas?

**Comment by johnDLK** [comment]
It puzzled me too

**Comment by johnDLK** [comment]
It puzzle me too. QAQ

**Comment by cburgmer** [comment]
Hey, Chrome in the meantime has fixed the tainting issue (at least partially), so if you render HTML via rasterizeHTML you should be able to read back from the Canvas. Safari still seems to have the problem (documented here https://github.com/cburgmer/rasterizeHTML.js/wiki/Limitations#safari), Firefox always just worked.

Do raise an issue if your problem doesn't match this description.
