### ISSUE TITLE
Support dynamically loaded images

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/rasterizeHTML.js#73]
Images loaded in JS with relative paths with different basePath to host document will fail. This is due to the page content being extracted and executed in an iframe without the document's base url.

**Comment by cburgmer** [comment]
Not going to be supported for now

**Comment by SamHasler** [comment]
Perhaps this could be reopened once the following are fixed:

[Chromium issue 484930 - Document.baseURI getter doesn't return the parent document's base URL for iframes](https://code.google.com/p/chromium/issues/detail?id=484930)

[whatwg/htlm #421 - Iframes should inherit the base URL of the parent document in some cases ](https://github.com/whatwg/html/issues/421)

**Comment by cburgmer** [comment]
The parent's base URL is only fitting if the page you are trying to render is the same URL. I feel the real problem is that currently the inlining of resources happens before the JS is run, rather than the other way around.

The choice to run the JS in an iframe outside of the base URL context was made because otherwise the iframe onload event would not trigger if the URL was not from the same origin, and rasterizehtml would never receive a callback, waiting for ever. There might also have been other reasons involved, but I currently cannot reproduce.
