### ISSUE TITLE
Images are re-ordered when rasterizing

### ISSUE THREAD

**Issue by DonKarlssonSan** [cburgmer/rasterizeHTML.js#93]
Using rasterizeHTML.allinone.js - v1.0.0 - 2015-03-01

Background
I'm making an application where you can take photos with the webcam, apply CSS filters, move the photos around and then generate a collage image consisiting of all the individual photos. Right now I am using html2canvas but I would like to start using rasterizeHTML instead.

 
Problem
I have a couple of img elements in a div.
I grab the outerHTML of the div.
Then I call rasterizeHTML.drawHTML() to draw on a canvas
The resulting image on the canvas does not look like the original, the img elements have moved around.

 This is the original:

![original](https://cloud.githubusercontent.com/assets/3482016/6543336/3324de42-c518-11e4-86b0-c129ffcf3bc9.png)

This is the image rendered by rasterizeHTML:
![re-ordered](https://cloud.githubusercontent.com/assets/3482016/6543338/46dbf556-c518-11e4-8b48-d489019e73fd.png)

Here the photos come in the order they where added to the DOM, but that is not how I placed them.

**Comment by DonKarlssonSan** [comment]
I have a reproduction of the problem in a zip file.

**Comment by DonKarlssonSan** [comment]
Here is a reproduction on codepen using divs instead of images:
http://codepen.io/anon/pen/YPOQMG

**Comment by cburgmer** [comment]
If you provide HTML make sure to include the styles alongside with it. I believe you are currently only seeing the rules of the inline styles being applied.

**Comment by DonKarlssonSan** [comment]
Yes, you are correct! Thanks for helping me out!

I got the impression that rasterizeHTML was able to inline CSS.
1. Reading https://github.com/cburgmer/rasterizeHTML.js: "All resources (HTML page, CSS, images, fonts and JS) that are needed for drawing the page can only be loaded if from the same origin..." 
2. Seeing the usage of your inlineresources library.

Does inlining only apply to rasterizeHTML.drawDocument()?

**Comment by cburgmer** [comment]
If you draw the HTML to a canvas its context is detached from the page. So styles in the page will not be applied to the content in the canvas unless the style element was placed inside the container passed to `drawHtml()`. Inlining applies to all three methods.

**Comment by DonKarlssonSan** [comment]
Ok, I see. Thanks!

**Comment by cburgmer** [comment]
Closing this issue for now as it seems there's nothing more to do. Please re-open if needed!
