### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by respincruz** [cburgmer/rasterizeHTML.js#97]
I download the library and examples not work. The problem is "rasterizeHTML is not defined" 
rasterizeHTML.drawHTML(input.value, canvas).then(function (result) {

I change the path the source, but I have the same problem.

Tks

**Comment by cburgmer** [comment]
You need to run `npm test` first, to provide the distributable under `./dist/`. This also means you need to have node & npm available locally.

The documentation could've been better on that. I changed it accordingly. Thanks for pointing this out.

**Comment by respincruz** [comment]
thanks Christiph but I have my application in a hosting and I can't run commands. How I can solve this problem?

**Comment by cburgmer** [comment]
Can you be more precise on what your set up is?

rasterizeHTML.js cannot just run from Git directly as
- there are 3rd party dependencies that need to be included through npm
- the distributable needs to be compiled unless you want to load a bunch of single files.

So the prefered way to install is `npm install rasterizehtml` and then using the file under `./node_modules/rasterizehtml/dist/rasterizeHTML.allinone.js`. Feel free to copy this file out and place this into your hosting. There's no need to keep the rest of the files around.

**Comment by respincruz** [comment]
thks Christoph I find a url with your library in only package. I needed your library work because I need to transform HTML content to an image. It seems that if I achieve this goal. If you have any doubt I could write. Thanks for your timely responses.

**Comment by respincruz** [comment]
the url where I find the library in only package is http://www.java2s.com/Open-Source/Javascript_Free_Code/Canvas_Render/Download_rasterize_HTML_js_Free_Java_Code.htm

**Comment by cburgmer** [comment]
I understand that you want the library itself as a single file. I do not understand why following https://github.com/cburgmer/rasterizeHTML.js#install does not work for you to provide that one file. 

To my knowledge, the standalone version of rasterizeHTML.js is currently not directly available through a CDN.

If you need a version available through CDN you can try https://wzrd.in/bundle/rasterizehtml 
and then call `window.rasterizeHTML = require('rasterizehtml');`. Or you could register the project under http://www.jsdelivr.com/.
